language: go
arch:
  - x86
  - x64
  - arm7

# matrix:
#   include:
#     - os: linux
#       arch: x64
#     - os: linux
#       arch: x86
#     - os: linux
#       arch: arm7

os:
  - linux
  - osx

go:
  - 1.11
